on:
  push:
    branches: [ "master" ]

jobs:
  benchmarks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.4
      - run: |
          # Build the benchmark apks
          ./gradlew :benchmark-java:packageReleaseAndroidTest :app:assembleRelease 
      - name: Firebase auth with gcloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.FIREBASE_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}